pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *')
    }

    environment {
        FRONTEND_IMAGE = "rakeshv12/ott-frontend-web"
        IMAGE_TAG      = "${BUILD_NUMBER}"
        GITHUB_REPO    = 'https://github.com/rakeshv12/ott-platform.git'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Pulling latest code from GitHub...'
                git branch: 'main', url: "${GITHUB_REPO}"
            }
        }

        stage('Build Frontend') {
            steps {
                echo 'Building Frontend image...'
                dir('frontend/web') {
                    script {
                        def frontendImage = docker.build("${FRONTEND_IMAGE}:${IMAGE_TAG}")
                        docker.withRegistry('https://index.docker.io/v1/', 'Docker') {
                            frontendImage.push("${IMAGE_TAG}")
                            frontendImage.push('latest')
                        }
                    }
                }
            }
        }

        stage('Update Manifests') {
            steps {
                echo 'Updating K8s image tag...'
                bat """
                    powershell -Command "(Get-Content k8s\\ott-frontend\\frontend-deployment.yaml) -replace 'ott-frontend-web:.*', 'ott-frontend-web:${IMAGE_TAG}' | Set-Content k8s\\ott-frontend\\frontend-deployment.yaml"
                """
            }
        }

        stage('Push Manifests to GitHub') {
            steps {
                echo 'Committing updated manifests...'
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'gitcred',
                        usernameVariable: 'GIT_USER',
                        passwordVariable: 'GIT_PASS'
                    )]) {
                        bat """
                            git config user.email "sairakeshkumar91@gmail.com"
                            git config user.name "rakeshv12"
                            git add k8s\\ott-frontend\\frontend-deployment.yaml
                            git diff --cached --quiet || git commit -m "ci: update frontend image tag to build ${IMAGE_TAG}"
                            git push https://%GIT_USER%:%GIT_PASS%@github.com/rakeshv12/ott-platform.git main
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "SUCCESS - Frontend Build ${IMAGE_TAG} pushed to Docker Hub"
        }
        failure {
            echo 'FAILED - check stage logs above'
        }
        always {
            bat "docker rmi ${FRONTEND_IMAGE}:${IMAGE_TAG} || exit 0"
        }
    }
}
