apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ott-frontend
  labels:
    app: frontend
    component: frontend
    environment: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP