apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ott-media
  labels:
    app: minio
    component: media
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP