apiVersion: v1
kind: Secret

metadata:
  name: minio-secret
  namespace: ott-media

type: Opaque

stringData:
  MINIO_ROOT_USER: {{ .Values.minio.credentials.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.credentials.rootPassword | quote }}