apiVersion: v1
kind: Namespace
metadata:
  name: ott-backend
  labels:
    environment: {{ .Values.global.environment }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ott-media
  labels:
    environment: {{ .Values.global.environment }}