apiVersion: v1
kind: Service

metadata:
  name: stream-service
  labels:
    app: stream-service
    component: backend
    environment: {{ .Values.global.environment }}

spec:
  # Stream is an internal backend service.
  type: {{ .Values.stream.service.type }}

  selector:
    app: stream-service

  ports:
    - name: http
      port: {{ .Values.stream.service.port }}
      targetPort: http
      protocol: TCP