apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: ott-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      imagePullSecrets:
        - name: my-docker
      containers:
        - name: frontend-web
          image: rakeshv12/ott-frontend-web:32
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_AUTH_API
              value: "http://auth-service.ott-backend.svc.cluster.local:3001"
            - name: CATALOG_API
              value: "http://catalog-service.ott-backend.svc.cluster.local:3002"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: ott-frontend
spec:
  selector:
    app: frontend-web
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
