apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ott-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rakeshv12/ott-platform.git
    targetRevision: main
    path: k8s/ott-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: ott-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
